// ============================================================================
// GENERATED — DO NOT EDIT
// This file is regenerated by the Jam typegen tool from known claim shapes.
// ============================================================================

import { KnownSkeletons } from "./jam";

declare module "./jam" {
  interface KnownSkeletons {
    0: [string, "is", "cool"];
    1: [string, "is", "awesome"];
    2: [string, "is", "impressive"];
    3: [string, "has", "health", number];
    4: [string, "is", "dead"];
    5: [string, "has", number, "legs"];
    6: [string, "should-render", string];
    7: [string, "is", "too", string];
  }
}
