// File automatically generated by swift-bridge.
#include <stdint.h>
typedef struct JamEngine JamEngine;
void __swift_bridge__$JamEngine$_free(void* self);

void* __swift_bridge__$Vec_JamEngine$new(void);
void __swift_bridge__$Vec_JamEngine$drop(void* vec_ptr);
void __swift_bridge__$Vec_JamEngine$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_JamEngine$pop(void* vec_ptr);
void* __swift_bridge__$Vec_JamEngine$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_JamEngine$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_JamEngine$len(void* vec_ptr);
void* __swift_bridge__$Vec_JamEngine$as_ptr(void* vec_ptr);

void* __swift_bridge__$JamEngine$new(void);
void* __swift_bridge__$JamEngine$load_program(void* self, struct RustStr name, struct RustStr ts_source);
void __swift_bridge__$JamEngine$remove_program(void* self, uint64_t program_id);
void* __swift_bridge__$JamEngine$assert_fact_json(void* self, struct RustStr json);
void* __swift_bridge__$JamEngine$retract_fact_json(void* self, struct RustStr json);
void* __swift_bridge__$JamEngine$step_json(void* self);
void* __swift_bridge__$JamEngine$current_facts_json(void* self);
void* __swift_bridge__$JamEngine$fire_event(void* self, struct RustStr entity_id, struct RustStr event_name);
void* __swift_bridge__$JamEngine$fire_event_with_data(void* self, struct RustStr entity_id, struct RustStr event_name, struct RustStr data);
void* __swift_bridge__$JamEngine$eval_js_ffi(void* self, struct RustStr code);
void* __swift_bridge__$JamEngine$drain_async(void* self);


